<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt"%>
<fmt:message key="language" var="fmt_language" />
<fmt:message key="hello" var="fmt_hello" />
<fmt:message key="localbutton.en" var="fmt_localbutton_en" />
<fmt:message key="localbutton.ru" var="fmt_localbutton_ru" />
<fmt:message key="logination" var="fmt_logination" />
<fmt:message key="registration" var="fmt_registration" />
<fmt:message key="logout" var="fmt_logout" />
<fmt:message key="login" var="fmt_login" />
<fmt:message key="password" var="fmt_password" />
<fmt:message key="enter" var="fmt_enter" />
<fmt:message key="back" var="fmt_back" />
<fmt:message key="edit" var="fmt_edit" />
<fmt:message key="read" var="fmt_read" />
<fmt:message key="modified" var="fmt_modified" />
<fmt:message key="save" var="fmt_save" />
<fmt:message key="title" var="fmt_title" />
<fmt:message key="brief" var="fmt_brief" />
<fmt:message key="content" var="fmt_content" />
<fmt:message key="admin" var="fmt_admin" />
<fmt:message key="delete" var="fmt_delete" />
<fmt:message key="name" var="fmt_name" />
<fmt:message key="surname" var="fmt_surname" />
<fmt:message key="error.registration" var="fmt_error_registration" />
<fmt:message key="error.logination" var="fmt_error_logination" />
<fmt:message key="redirect" var="fmt_redirect" />
<fmt:message key="necessarily" var="fmt_necessarily" />
<fmt:message key="site.error" var="fmt_site_error" />